name: Build, Test, Package and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build_test_package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake

      - name: Configure CMake
        run: |
          mkdir -p Catalog/Factory/easy/code/build
          cd Catalog/Factory/easy/code/build
          cmake ..

      - name: Build project and tests
        run: |
          cd Catalog/Factory/easy/code/build
          make

      - name: Run tests
        run: |
          cd Catalog/Factory/easy/code/build
          ctest --output-on-failure

      - name: Build deb package
        run: |
          cd Catalog/Factory/easy/code/build
          make package

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: factory-method-deb
          path: Catalog/Factory/easy/code/build/factory-method-app_1.0.0_amd64.deb

  release:
    needs: build_test_package
    runs-on: ubuntu-latest

    steps:
      - name: Download .deb artifact
        uses: actions/download-artifact@v3
        with:
          name: factory-method-deb
          path: ./deb

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload .deb to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./deb/factory-method-app_1.0.0_amd64.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}